### ISSUE TITLE
Official glob support

### ISSUE THREAD

**Issue by laco0416** [laco0416/tsconfig-cli#4]
When TSC finished supporting glob, this CLI is over.

https://github.com/Microsoft/TypeScript/pull/3232

**Comment by laco0416** [comment]
https://github.com/Microsoft/TypeScript/wiki/What's-new-in-TypeScript#glob-support-in-tsconfigjson

TS2.0 supports new `include` field supporting glob patterns. 

tsconfig-cli will finish its job.

**Comment by lacolaco** [comment]
TS 2.0 is out.
